name: CD Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Update npm (prevent ci errors)
        run: npm install -g npm@latest
      
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to S3 Cloud Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ vars.AWS_BUCKET_NAME }}
          AWS_S3_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync dist/ "s3://${AWS_S3_BUCKET}" --endpoint-url "${AWS_S3_ENDPOINT_URL}" --delete